### ISSUE TITLE
v1.5.0 error with browserify

### ISSUE THREAD

**Issue by Distopico** [foretagsplatsen/numbro#70]
I try to use numbro with browserify but this part of code is only compatible with nodejs
```js
// Load all languages
        var fs = require('fs'),
            path = require('path');
        var langFiles = fs.readdirSync(path.join(__dirname, 'languages'));
        langFiles.forEach(function (langFile) {
            numbro.language(path.basename(langFile, '.js'), require(path.join(__dirname, 'languages', langFile)));
        });

```

**Comment by BenjaminVanRyseghem** [comment]
but this code is in a `if` statement (checking that there is a global variable `module`)

Isn't that good enough?

**Comment by Distopico** [comment]
No, browserify is CommonJS and have module.exports but no have native 'fs' and '' 'path' in the code validate if a CommonJS but no if have fs or path modules.

possible solution

```javascript
// CommonJS module is defined
    if (hasModule) {
        module.exports = numbro;

        // Load all languages if have modules (NodeJs or io.js)
        var fs = require('fs'),
            path = require('path');

        if(fs && path) {
              var langFiles = fs.readdirSync(path.join(__dirname, 'languages'));
              langFiles.forEach(function (langFile) {
                 numbro.language(path.basename(langFile, '.js'), require(path.join(__dirname, 'languages', langFile)));
             });
        }
    }

```

**Comment by robotvert** [comment]
Trying to use it with webpack/ES6 (with babel)/npm and it yielded warnings/errors that sound related to this issue.

Note that simply importing spit tons of warnings & errors while importing the dist directly file still failed but with much less stuff in the console.
FYI I'm using momentjs and by simply importing it, everything works like a charm. Mentioning this because the README states the lib has been influenced by it.


### "Simple" import
```
// es6 file
import numbro from "numbro";

// console output
WARNING in ./~/numbro/numbro.js
Critical dependencies:
970:60-112 the request of a dependency is an expression
 @ ./~/numbro/numbro.js 970:60-112

WARNING in ./~/numbro/CHANGELOG-Numeraljs.md
Module parse failed: /Users/julien/dev/repos/decap_intranet/client/node_modules/numbro/CHANGELOG-Numeraljs.md Line 1: Unexpected identifier
You may need an appropriate loader to handle this file type.
| _This is the historical changelog for the [`numeral-js`
| project](https://github.com/adamwdraper/Numeral-js), which `numbro` is built upon. The `numbro`
| changelog is at [CHANGELOG.md](CHANGELOG.md)._
 @ ./~/numbro ^\.\/.*$

WARNING in ./~/numbro/CHANGELOG.md
Module parse failed: /Users/julien/dev/repos/decap_intranet/client/node_modules/numbro/CHANGELOG.md Line 1: Unexpected token ILLEGAL
You may need an appropriate loader to handle this file type.
| ### 1.5.0
|
| - Adds support for Hebrew (he-LI). Thanks to @eli-zehavi
 @ ./~/numbro ^\.\/.*$

WARNING in ./~/numbro/LICENSE
Module parse failed: /Users/julien/dev/repos/decap_intranet/client/node_modules/numbro/LICENSE Line 1: Unexpected number
You may need an appropriate loader to handle this file type.
| Copyright (c) 2015 Företagsplatsen
|
| Permission is hereby granted, free of charge, to any person
 @ ./~/numbro ^\.\/.*$

WARNING in ./~/numbro/LICENSE-Numeraljs
Module parse failed: /Users/julien/dev/repos/decap_intranet/client/node_modules/numbro/LICENSE-Numeraljs Line 1: Unexpected number
You may need an appropriate loader to handle this file type.
| Copyright (c) 2014 Adam Draper
|
| Permission is hereby granted, free of charge, to any person
 @ ./~/numbro ^\.\/.*$

WARNING in ./~/numbro/README.md
Module parse failed: /Users/julien/dev/repos/decap_intranet/client/node_modules/numbro/README.md Line 1: Unexpected token ILLEGAL
You may need an appropriate loader to handle this file type.
| # [numbro](https://numbrojs.com/)
|
| A javascript library for formatting and manipulating numbers.
 @ ./~/numbro ^\.\/.*$

WARNING in ./~/numbro/bower.json
Module parse failed: /Users/julien/dev/repos/decap_intranet/client/node_modules/numbro/bower.json Line 2: Unexpected token :
You may need an appropriate loader to handle this file type.
| {
|   "name": "numbro",
|   "repo": "foretagsplatsen/numbro",
|   "version": "1.5.0",
 @ ./~/numbro ^\.\/.*$

WARNING in ./~/numbro/component.json
Module parse failed: /Users/julien/dev/repos/decap_intranet/client/node_modules/numbro/component.json Line 2: Unexpected token :
You may need an appropriate loader to handle this file type.
| {
|   "name": "numbro",
|   "repo": "foretagsplatsen/numbro",
|   "version": "1.5.0",
 @ ./~/numbro ^\.\/.*$

WARNING in ./~/numbro/package.json
Module parse failed: /Users/julien/dev/repos/decap_intranet/client/node_modules/numbro/package.json Line 2: Unexpected token :
You may need an appropriate loader to handle this file type.
| {
|   "name": "numbro",
|   "version": "1.5.0",
|   "description": "Format and manipulate numbers.",
 @ ./~/numbro ^\.\/.*$

WARNING in ./~/numbro/resources/LICENSE
Module parse failed: /Users/julien/dev/repos/decap_intranet/client/node_modules/numbro/resources/LICENSE Line 1: Unexpected number
You may need an appropriate loader to handle this file type.
| Copyright 2015 Benjamin Van Ryseghem
|
| Creative Commons Corporation (“Creative Commons”) is not a law firm and does not provide legal services or legal advice. Distribution of Creative Commons public licenses does not create a lawyer-client or other relationship. Creative Commons makes its licenses and related information available on an “as-is” basis. Creative Commons gives no warranties regarding its licenses, any material licensed under their terms and conditions, or any related information. Creative Commons disclaims all liability for damages resulting from their use to the fullest extent possible.
 @ ./~/numbro ^\.\/.*$

WARNING in ./~/numbro/resources/README.md
Module parse failed: /Users/julien/dev/repos/decap_intranet/client/node_modules/numbro/resources/README.md Line 1: Unexpected token ILLEGAL
You may need an appropriate loader to handle this file type.
| # Ranko the Raccoon
|
| Ranko is the mascott of the [numbro](https://github.com/foretagsplatsen/numbro) project.
 @ ./~/numbro ^\.\/.*$

WARNING in ./~/numbro/dist/numbro.js
Critical dependencies:
970:60-112 the request of a dependency is an expression
 @ ./~/numbro/dist/numbro.js 970:60-112

WARNING in ./~/numbro/dist/numbro.min.js
Critical dependencies:
8:9915-9955 the request of a dependency is an expression
 @ ./~/numbro/dist/numbro.min.js 8:9915-9955

ERROR in ./~/numbro/numbro.js
Module not found: Error: Cannot resolve module 'fs' in /Users/julien/dev/repos/decap_intranet/client/node_modules/numbro
 @ ./~/numbro/numbro.js 966:17-30

ERROR in ./~/numbro/Gruntfile.js
Module not found: Error: Cannot resolve module 'fs' in /Users/julien/dev/repos/decap_intranet/client/node_modules/numbro
 @ ./~/numbro/Gruntfile.js 1:9-22

ERROR in ./~/numbro/dist/numbro.js
Module not found: Error: Cannot resolve module 'fs' in /Users/julien/dev/repos/decap_intranet/client/node_modules/numbro/dist
 @ ./~/numbro/dist/numbro.js 966:17-30

ERROR in ./~/numbro/dist/numbro.min.js
Module not found: Error: Cannot resolve module 'fs' in /Users/julien/dev/repos/decap_intranet/client/node_modules/numbro/dist
 @ ./~/numbro/dist/numbro.min.js 8:9783-9796

ERROR in ./~/numbro/tests/languages/locale-codes.js
Module not found: Error: Cannot resolve module 'require-dir' in /Users/julien/dev/repos/decap_intranet/client/node_modules/numbro/tests/languages
 @ ./~/numbro/tests/languages/locale-codes.js 3:17-39
```

### "Direct" import
```
// es6 file
import numbro from "../node_modules/numbro/dist/numbro";

// console output
WARNING in ./~/numbro/dist/numbro.js
Critical dependencies:
970:60-112 the request of a dependency is an expression
 @ ./~/numbro/dist/numbro.js 970:60-112

WARNING in ./~/numbro/dist/numbro.min.js
Critical dependencies:
8:9915-9955 the request of a dependency is an expression
 @ ./~/numbro/dist/numbro.min.js 8:9915-9955

ERROR in ./~/numbro/dist/numbro.js
Module not found: Error: Cannot resolve module 'fs' in /Users/julien/dev/repos/decap_intranet/client/node_modules/numbro/dist
 @ ./~/numbro/dist/numbro.js 966:17-30

ERROR in ./~/numbro/dist/numbro.min.js
Module not found: Error: Cannot resolve module 'fs' in /Users/julien/dev/repos/decap_intranet/client/node_modules/numbro/dist
 @ ./~/numbro/dist/numbro.min.js 8:9783-9796
```

**Comment by avetisk** [comment]
I have the same issue, but strangely, the error is reported differently: 
```
Unexpected token (931:34) while parsing node_modules/numbro/numbro.js while parsing file: node_modules/numbro/numbro.js
```
if you look at [`931:34`](https://github.com/foretagsplatsen/numbro/blob/develop/numbro.js#L931) in `numbro.js` you have this: `function cback(accum, curr) {`.

Even more strangely: it works fine with `1.3.2` or `1.3.3` or `1.4.0`, but not with `1.3.1` nor `1.5.0`.

**Comment by clayzermk1** [comment]
:+1: also seeing this on numbro 1.5.0 and browserify 11.0.1.

Copying [moment's module definition pattern](https://github.com/moment/moment/blob/f3fbef9d9875bbff340b527dbe3f1c447a942f69/moment.js#L8) or implementing [UMD](https://github.com/umdjs/umd/blob/master/commonjsStrict.js) would be a couple ways to go about this.

I'll try a couple things and see what I come up with.

**Comment by jenswegar** [comment]
1.5.1 seems to have this issue as well when using browserify. The error I get in the browser is 

    TypeError: fs.readdirSync is not a function

which occurs in this block of code:

    // CommonJS module is defined
    if (hasModule) {
        module.exports = numbro;

        // Load all languages
        var fs = require('fs'),
            path = require('path');
        var langFiles = fs.readdirSync(path.join(__dirname, 'languages'));
        langFiles.forEach(function (langFile) {
            numbro.language(path.basename(langFile, '.js'), require(path.join(__dirname, 'languages', langFile)));
        });
    }


1.1.1 did not have this problem and since it's enough for my needs right now, I'm sticking to that version for the time being.

**Comment by BenjaminVanRyseghem** [comment]
can you check that #101 fixes this issue?
